name: hatarukun_mobile
description: iOS and Android Flutter prototype for Hatarukun.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  clerk_auth: 0.0.18-beta
  clerk_flutter: ^0.0.18-beta

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/brand/hatarukun-icon-1024.png
    - assets/brand/higashihiroshima.jpg
